// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD98tBJA9hjcZYZkgX5VVDoXQJYWZix0tA',
    appId: '1:74710977614:web:639dd7dc1bb10a62f8871f',
    messagingSenderId: '74710977614',
    projectId: 'machinelearning-9d985',
    authDomain: 'machinelearning-9d985.firebaseapp.com',
    storageBucket: 'machinelearning-9d985.appspot.com',
    measurementId: 'G-HFT62W4L6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvm4MQzo1emzdeF-U1jw-FRmKbBgiiBfk',
    appId: '1:74710977614:android:20ba9930e5f9720af8871f',
    messagingSenderId: '74710977614',
    projectId: 'machinelearning-9d985',
    storageBucket: 'machinelearning-9d985.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaJHP9qM4OM_mniv4iZNWQHdFyTMPfKiA',
    appId: '1:74710977614:ios:d0fb055bc4ccf853f8871f',
    messagingSenderId: '74710977614',
    projectId: 'machinelearning-9d985',
    storageBucket: 'machinelearning-9d985.appspot.com',
    iosClientId: '74710977614-akn7n2jqp5faqhbsonvcqhi1obuc6iqi.apps.googleusercontent.com',
    iosBundleId: 'com.example.mlkit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaJHP9qM4OM_mniv4iZNWQHdFyTMPfKiA',
    appId: '1:74710977614:ios:d0fb055bc4ccf853f8871f',
    messagingSenderId: '74710977614',
    projectId: 'machinelearning-9d985',
    storageBucket: 'machinelearning-9d985.appspot.com',
    iosClientId: '74710977614-akn7n2jqp5faqhbsonvcqhi1obuc6iqi.apps.googleusercontent.com',
    iosBundleId: 'com.example.mlkit',
  );
}
